import "@/styles/globals.css";
import Head from "next/head";
import NavBar from "@/components/NavBar";
import ErrorBoundary from "@/components/ErrorBoundary";
import { Comfortaa } from "next/font/google";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>IPL Stats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ipl.ico" />
      </Head>
      <main className={comfortaa.className}>
        <ErrorBoundary>
          <NavBar />
          <Component {...pageProps} />
        </ErrorBoundary>
      </main>
    </>
  );
}
